apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: funda-scraper-service
spec:
  template:
    spec:
      containers:
      - image: europe-west4-docker.pkg.dev/funda-424117/prod/fundascraper
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: TELEGRAM_TOKEN